app/models.py
from datetime import datetime
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from app import db, login_manager, app
from flask_login import UserMixin
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
class User(db.Model,UserMixin):
    id = db.Column(db.Integer , primary_key=True)
    username =db.Column(db.String(20),unique=True,nullable=False)
    email = db.Column(db.String(120), unique=True , nullable=False)
    password =db.Column(db.String(60),nullable=False)
    def __repr__(self):
        return f"User('{self.username}','{self.email}')"
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    posted_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    content = db.Column(db.Text, nullable=False)
    image = db.Column(db.String(225), default='default.jpg')
    # user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    def __repr__(self):
        return f"Post('{self.title}', '{self.posted_date}')"

app/ratings/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, TextField, SelectField, widgets
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from app.models import User
from flask_login import current_user
class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=3)])
    content = TextAreaField('Content', validators=[DataRequired()])
    image = FileField('Featured Image', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Upload')

app/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from app.models import User



class RegistrationForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[
                             DataRequired(), Length(min=6, max=15)])
    confirm_password = PasswordField(
        "Password", validators=[DataRequired(), EqualTo("password")])
    submit = SubmitField("Sign Up")
    
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("That username is taken please choose another")
        
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("That email is taken please choose another")
            
    
class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[
                             DataRequired(), Length(min=6, max=15)])
    remember = BooleanField("Remember Me")
    submit = SubmitField("Log In")

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager


app = Flask(__name__)
app.config["SECRET_KEY"] = "efec7e52ccb4a3e86ec302b43fce90fa1c167ba1"
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///ratings.db"
db = SQLAlchemy(app)
login_manager= LoginManager(app)
bcrypt = Bcrypt(app)

# import blueprints
from app.main.views import main
from app.users.views import users
from app.ratings.views import ratings

#register bluepprints
app.register_blueprint(main)
app.register_blueprint(users)
app.register_blueprint(ratings)

app/main/views.py
from flask import render_template, request, Blueprint
from app.models import Post
main = Blueprint("main",__name__)
@main.route('/')
@main.route("/home")
def home():
    posts = Post.query.all()
    return render_template('index.html', posts=posts)

app/ratings/views.py
import os
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint, current_app)
from flask_login import current_user, login_required, logout_user
from app import db, bcrypt
import secrets 
from PIL import Image
from app.models import Post, User
from app.ratings.forms import PostForm
from ..main import views

ratings = Blueprint('ratings', __name__)


def save_picture(form_image):
    randome_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_image.filename)
    picture_name = randome_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/featured_images', picture_name)
    output_size = (1000, 400)
    final_image = Image.open(form_image)
    final_image.thumbnail(output_size)
    final_image.save(picture_path)
    return picture_name
@ratings.route("/post/new", methods=['GET', 'POST'])
#@login_required
def newpost():
    form = PostForm()
    if form.validate_on_submit():
        pic =None
        if form.image.data:
            picture_file = save_picture(form.image.data)
            final_pic = picture_file
            pic= final_pic
        post = Post(title=form.title.data, content=form.content.data,image=pic)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been published!', 'success')
        return redirect(url_for('main.home'))
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('newpost.html', title='New Post', form=form, legend='New Post', myposts=myposts)

app/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User
from app.users.forms import RegistrationForm, LoginForm



users = Blueprint("users",__name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            flash('Login successfull.', 'success')
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

app/templates/index.html
{% extends "layout.html" %} {% block content %}
<div class="heropage">
  <div class="herocontent">
    <h1>The #1 Rating <br> and Reviews Website <br> in Kenya</h1>
    <p class="mt-4">Make a Five <i class="fas fa-star"></i> Rated decision Today</p>
  </div>
  <div class="steps">
    <div class="text-center">
    <figure>
      <img src="{{ url_for('static', filename='images/account.png')}}" alt="Account" width="100px" class="step">
      <figcaption>
        SIGN UP
      </figcaption>
    </figure>
    </div>
    <div class="text-center">
    <figure>
      <img src="{{ url_for('static', filename='images/search.png')}}" alt="Account" width="100px" class="step">
      <figcaption>
        SEARCH
      </figcaption>
    </figure>
    </div>
    <div class="text-center">
    <figure>
      <img src="{{ url_for('static', filename='images/rate.png')}}" alt="Account" width="100px" class="step">
      <figcaption>
        RATE
      </figcaption>
    </figure>
    </div>

  </div>
</div>
<!-- Scrolling Text -->
<div id ="two">
  <p class="para">YOU CAN RATE</p>
<div class="box">
<ul class="scroller">
  <li class="item-1">Hospitals</li>
  <li class="item-2">Restaurants</li>
  <li class="item-3">Colleges</li>
  <li class="item-4">Companies</li>
  <li class="item-5">Bakeries</li>
</ul>  
</div>
</div>
<!-- {% for post in posts %}
<div class="col-xs-12 col-sm-4 col-md-8 col-lg-12">
  <div class="card p-2">
    <div class="image">
      <a class="img-card" href="">
          <img src="{{ url_for('static', filename='featured_images/')}}{{post.image}}" />
      </a>
    </div>
      <div class="card-content">
          <h4 class="card-title">
            {{post.title}}
            
          </h4>
          <p class="card-body">
            {{post.content}}
            {% include 'stars.html' %}
          </p>
      </div>
  </div>

{% endfor %} {% endblock content %} -->

app/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/2ae247d80b.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">

    <title>Rate Kenya</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block navbar %}
    {% endblock navbar %}
    <div class="container-fluid">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    </div>
    {% block content %}
    {% endblock content %}
   </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{{url_for('static', filename='js/main.js')}}"></script>
  </body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
  <div class="card pt-5 mt-5 shadow rounded">
    <div class="content-section p-4">
        <form action="" method="POST">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top p-5 text-center">
        <small class="text-muted">
            Need An Account? <a href="">Register</a>
        </small>
    </div>
  </div>
{% endblock content %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg" style="background: #292D64;">
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.home')}}"
          ><img
            src="{{url_for('static', filename='images/rating_logo.png')}}"
            alt=""
            width="200px"
        /></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <div class="navbar-nav">
        {% if current_user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-item nav-link active" href="{{url_for('users.logout')}}"
            >Logout</a
          >
        </li>
        {% else %}
        <li class="nav-item active">
          <a
            class="nav-item nav-link active"
            href="{{url_for('ratings.newpost')}}"
            >Create Post</a
          >
        </li>
        <li class="nav-item active">
          <a class="nav-item nav-link active" href="{{url_for('users.login')}}"
            >Login</a
          >
        </li>
        <li class="nav-item active">
          <a
            class="nav-item nav-link active"
            href="{{url_for('users.register')}}"
            >Register</a
          >
        </li>
        {% endif %}
      </div>
    </ul>
  </div>
</nav>

app/templates/newpost.html
{% extends "layout.html" %}
{% block content%} 
<div class="container">
    <div class="card m-5 p-5 shadow rounded">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{form.csrf_token}}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">New Blog</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid", rows='10',cols='35', id="editor") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg", rows='10',cols='35', id="editor") }}
                    {% endif %}
                </div>
            <div class="form-group">
                {{ form.image.label() }}
                {{ form.image(class="form-control-file") }}
                {% if form.image.errors %}
                    {% for error in form.image.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group text-center">
            {{ form.submit(class="btn btn-outline-success") }}
        </div>
    </form>
</div>
</div>
{% endblock content %}

app/templates/register.html
{% extends "layout.html" %} 
{% block content %}
<div class="container">
  <div class="card mt-5 p-5 shadow rounded">
    <form method="POST" action="">
      {{form.hidden_tag()}}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4 text-center">Join Today</legend>
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }} {% if
          form.username.errors %} {{ form.username(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }} {% if
          form.email.errors %} {{ form.email(class="form-control form-control-lg
          is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.email(class="form-control form-control-lg") }} {%
          endif %}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }} {% if
          form.password.errors %} {{ form.password(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.confirm_password.label(class="form-control-label") }} {% if
          form.confirm_password.errors %} {{
          form.confirm_password(class="form-control form-control-lg is-invalid")
          }}
          <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.confirm_password(class="form-control
          form-control-lg") }} {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}
      </div>
    </form>
    <div class="border-top pt-3 text-center">
      <small class="text-muted">
        Already Have An Account?
        <a href="{{ url_for('users.login') }}">Log In</a>
      </small>
    </div>
  </div>
</div>
{% endblock content %}

app/templates/stars.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="style.css">
  <script src="https://kit.fontawesome.com/2ae247d80b.js" crossorigin="anonymous"></script>
  <title>Stars</title>
</head>
<body>

  <div class="rating">
    <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="Rocks!">5 stars</label>
    <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
    <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Meh">3 stars</label>
    <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
    <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Sucks big time">1 star</label>
</div>
  
</body>
</html>